# ref: https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions
name: NodeJS Version Bump Action
description: A simple GitHub Actions to bump the version of NodeJS projects

author: Nick Nichols et al.

branding:
  color: purple
  icon: git-commit

inputs:
  github-token:
    description: 'A GitHub auth token to be able to create the pull request'
    required: true
  root-path:
    description: 'The relative location of your package.json file'
    required: true
    default: '.'
  type:
    description: 'The type of release patch,major, or minor'
    required: false
    default: ''
  git-email:
    description: 'The email address used to create the version bump commit with.'
    required: true
    default: 41898282+github-actions[bot]@users.noreply.github.com
  git-username:
    description: 'The name to use for the version bump commit. e.g. github.actor'
    required: true
    default: github-actions[bot]

outputs:
  version:
    description: 'The current version (whether updated or not)'
    value: ${{ steps.get-outputs.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Bump Version
      env:
        TOKEN: ${{ inputs.github-token }}
        EMAIL: ${{ inputs.git-email }}
        NAME: ${{ inputs.git-username }}
        POMPATH: ${{ inputs.pom-path }}
        TYPE: ${{ inputs.type }}
      run: ${{github.action_path}}/version-bump.sh
      shell: bash
    - name: Set outputs
      id: get-outputs
      shell: bash
      env:
        ROOTPATH: ${{ inputs.root-path }}
      run: echo "version=$(${{github.action_path}}/get-version.sh)" >> $GITHUB_OUTPUT
    - name: Result
      shell: bash
      run: "echo 'Version is now ${{ steps.get-outputs.outputs.version }}'"

